# Generated by Django 3.1.7 on 2021-05-31 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0004_categories_small_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='doctor_detail2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='details',
            name='doctor_img2',
            field=models.ImageField(blank=True, upload_to='pictures'),
        ),
        migrations.AddField(
            model_name='details',
            name='doctor_name2',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
