# Generated by Django 3.1.7 on 2021-06-01 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0005_auto_20210531_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='doctor_detail2',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='details',
            name='doctor_img2',
            field=models.ImageField(upload_to='pictures'),
        ),
        migrations.AlterField(
            model_name='details',
            name='doctor_name2',
            field=models.CharField(max_length=250),
        ),
    ]
