# Generated by Django 3.1.7 on 2021-06-01 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0006_auto_20210601_1929'),
    ]

    operations = [
        migrations.RenameField(
            model_name='details',
            old_name='doctor_detail2',
            new_name='doctordetail2',
        ),
        migrations.RenameField(
            model_name='details',
            old_name='doctor_img2',
            new_name='doctorimg2',
        ),
        migrations.RenameField(
            model_name='details',
            old_name='doctor_name2',
            new_name='doctorname2',
        ),
    ]
